name: html_unescape
description: >
  A small library for un-escaping HTML. Supports all Named Character References,
  Decimal Character References and Hexadecimal Character References.
version: 1.0.2
homepage: https://github.com/filiph/html_unescape

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'

dev_dependencies:
  meta: ^1.3.0-nullsafety.2
  test: ^1.16.0-nullsafety.4
  path: ^1.8.0-nullsafety
  pedantic: ^1.10.0-nullsafety
