name: html_unescape
description: A small library for un-escaping HTML.
version: 0.1.5
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/html_unescape

environment:
  sdk: '>=1.23.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  path: '>=1.3.9 <1.5.0'
