name: html_unescape
description: >
  A small library for un-escaping HTML. Supports all Named Character References,
  Decimal Character References and Hexadecimal Character References.
version: 1.0.2
homepage: https://github.com/filiph/html_unescape

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.15.3
  path: ^1.7.0
  pedantic: ^1.9.2
